version: '3.8'

services:
  mysql:
    build:
      context: .
      dockerfile: Dockerfile.mysql
    container_name: mysql-container
#    restart: always
#    environment:
    env_file:
      - .env
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "3306:3306"

  todolist:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todolist-container
    restart: unless-stopped
#    environment:
#      DB_HOST: ${DB_HOST}
#      DB_NAME: ${DB_NAME}
#      DB_USER: ${DB_USER}
#      DB_PASSWORD: ${DB_PASSWORD}
    env_file:
      - .env
    ports:
      - "8000:8080"
    depends_on:
      - mysql

volumes:
  mysql-data:
